/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package menu;

import apendix.ConnectionClass;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Simran
 */
public class Indian extends javax.swing.JFrame {

    private int CusID;
    private ConnectionClass connClass = ConnectionClass.getConnObj();
    /**
     * Creates new form Indian
     */
    public Indian() {
        initComponents();
        data();
        
   }
    
    public Indian(int CusID) {
        initComponents();
        data();
        this.CusID = CusID;
   }
    
    void data()
    {
     String category = "Indian";
        try{
            PreparedStatement pstmm = connClass.conn.prepareStatement("select Food,Rate from menu_detail where `Category` =?" );
            
            pstmm.setString(1,category);
            ResultSet rs = pstmm.executeQuery();
           jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
            pstmm.executeQuery();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "food"+e);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(683, 258));
        setResizable(false);
        setSize(new java.awt.Dimension(683, 258));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));
        jPanel1.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Food", "Rate"
            }
        ));
        jTable1.setIntercellSpacing(new java.awt.Dimension(5, 5));
        jTable1.setMinimumSize(new java.awt.Dimension(35, 35));
        jTable1.setRowHeight(47);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(80, 20, 498, 219);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/download.jpg"))); // NOI18N
        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(640, 0, 50, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 700, 250);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int id1 = jTable1.getSelectedRow();
        
       // int id2 = jTable2.getSelectedColumn();
        String name = (String) jTable1.getValueAt(id1, 0);
        System.out.println(name);
        try{
            PreparedStatement pstmm = connClass.conn.prepareStatement("select * from menu_detail where `Food`=?" );
            pstmm.setString(1,name);
            ResultSet rs = pstmm.executeQuery();
            if(rs.next())
            {
                
                
                PreparedStatement  pstm = connClass.conn.prepareStatement("insert into order1(food,rate,fid,cid) values(?,?,?,?)");
                pstm.setString(1,rs.getString("Food"));
                pstm.setString(2,rs.getString("Rate"));
                pstm.setString(3,rs.getString("Id"));
                pstm.setString(4,String.valueOf(this.CusID));
                
                pstm.executeUpdate();
            }
                
           
           
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "error"+e);
        }
        
          
                                        

    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Indian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Indian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Indian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Indian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Indian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
